### ISSUE TITLE
Readium project name

### ISSUE THREAD

**Issue by danielweck** [lorenkp/Readium#2]
Hello, first of all, this looks like a great project, so congratulations! :)

I just wanted to bring to your attention that the term "Readium" has been used for several years in the field of digital publishing (I am a software developer involved in the Readium projects):

I have a slight concern that users may get confused, given that http://www.readium.io is for online publishing / reading too. There's also a bunch of Wordpress / CMS themes with the name "Readium" in them, but they probably have a lesser potential to confuse end-users.

For reference:

Readium Foundation:
http://readium.org

Readium app (Chrome extension):
https://chrome.google.com/webstore/detail/readium/fepbnnnkkadjhjahcafoaglimekefifl

Readium open-source software:
https://github.com/readium

Example of URLs where Readium web apps are deployed (continuous integration, for testing only):
http://readium.divshot.io
http://readium.surge.sh/?epub=http%3A%2F%2Fdevelopment.readium.divshot.io%2Fepub_content%2Faccessible_epub_3

NPM:
https://www.npmjs.com/~readium

Regards, Daniel

**Comment by lorenkp** [comment]
Hi Daniel,

Thanks for your email and letting me know there's another group called
Readium! I appreciate your concern. What do you propose we do?

Thanks,
Loren

**Comment by danielweck** [comment]
Hello @lorenkp 
well, _strictly_-speaking, I guess you can just carry on using the `Readium` name for your software project (is it even registered trademark? I'm not sure). However, if you intend to build a "brand" and/or a user base, then it might make sense to rename your project, so that end-users don't confuse it with 'the other Readium' :)

**Comment by lorenkp** [comment]
Hi @danielweck 
This was only an exercise in building a site; I'm not intending to build/develop a "Readium" brand or recruit and expand a user base. I hope that clears things up!

Loren

**Comment by danielweck** [comment]
Good to know. Cheers, Dan
